//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PooVueling {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class log4net : global::System.Configuration.ApplicationSettingsBase {
        
        private static log4net defaultInstance = ((log4net)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new log4net())));
        
        public static log4net Default {
            get {
                return defaultInstance;
            }
        }
    }
}
